version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ecom-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecom
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecom-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=ecom
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - FRONTEND_URL=http://localhost:5174
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecom-frontend
    restart: unless-stopped
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
    working_dir: /app

volumes:
  mongodb_data:
